### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AntroidDev** [itsaky/AndroidIDE#117]
AndroidIDE crash report
Manufacturer: HUAWEI
Device: SNE-LX3
App version: 2.0-beta (200)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'int io.github.rosemoe.sora.text.CharPosition.line' on a null object reference
	at io.github.rosemoe.sora.text.CachedIndexer.afterInsert(CachedIndexer.java:419)
	at io.github.rosemoe.sora.text.Content.dispatchAfterInsert(Content.java:852)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:372)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:331)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(CodeEditor.java:3003)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:246)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(EditorInputConnection.java:210)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:339)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by itsaky** [comment]
Please report this to [sora-editor](https://github.com/Rosemoe/sora-editor) repo with a way to reproduce this issue.
