### ISSUE TITLE
[BUG] Cannot extract downloaded Gradle distribution

### ISSUE THREAD

**Issue by masfha** [itsaky/AndroidIDE#120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - Device: [Poco M3 Pro 5G]
 - OS: [Android 11]
 - AndroidIDE Version [v1.0.3-alpha]

**Additional context**
========== [01:13:18] TASK_BEGIN: assembleDebug ==========
Could not unzip ROOT/framework/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3-bin.zip to ROOT/framework/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv.
Reason: zip END header not found
Exception in thread "main" java.util.zip.ZipException: zip END header not found
at java.base/java.util.zip.ZipFile$Source.zerror(Unknown Source)
at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
at org.gradle.wrapper.Install.unzip(Install.java:238)
at org.gradle.wrapper.Install.access$900(Install.java:27)
at org.gradle.wrapper.Install$1.call(Install.java:81)
at org.gradle.wrapper.Install$1.call(Install.java:48)
at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
at org.gradle.wrapper.Install.createDist(Install.java:48)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Gradle process exited with exit code 1

![Screenshot_2022-03-15-01-19-32-651_com itsaky androidide](https://user-images.githubusercontent.com/79098759/158236084-79a2c7e9-136a-4711-822a-5d1eba1cddcd.jpg)

**Comment by MrIkso** [comment]
I think it not relevant problem, needed closing.
