### ISSUE TITLE
[BUG] On copying texts it gives IndexOutOfBoundsException error

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [itsaky/AndroidIDE#126]
**Describe the bug**
In the latest update of AndroidIDE on copying texts the editor gives IndexOutOfBoundsException error. it happened with me today 3-4 times.

```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2102J20SI
App version: 2.0-beta (200)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: start 0, end 69, s.length() 63
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
	at java.lang.StringBuilder.append(StringBuilder.java:176)
	at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:494)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:407)
	at io.github.rosemoe.sora.widget.CodeEditor.deleteText(CodeEditor.java:1567)
	at io.github.rosemoe.sora.widget.CodeEditor.cutText(CodeEditor.java:2806)
	at com.itsaky.androidide.views.editor.IDEEditor.performTextAction(IDEEditor.java:857)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow.performTextAction(EditorTextActionWindow.java:242)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow.$r8$lambda$1a97XtgRzFmV8POkyslZz1lSeNs(Unknown Source:0)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow$$ExternalSyntheticLambda4.accept(Unknown Source:4)
	at com.itsaky.androidide.adapters.TextActionItemAdapter.lambda$onBindViewHolder$0$com-itsaky-androidide-adapters-TextActionItemAdapter(TextActionItemAdapter.java:88)
	at com.itsaky.androidide.adapters.TextActionItemAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7509)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28710)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by itsaky** [comment]
This should probably be reported to [`sora-editor`](https://github.com/Rosemoe/sora-editor).
