### ISSUE TITLE
[BUG] Exception when InputConnection tries to get selected text

### ISSUE THREAD

**Issue by jakelen61732** [itsaky/AndroidIDE#134]
AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi8
App version: 2.0-beta (200)

 Stacktrace: 
java.lang.IllegalArgumentException: start > end
	at io.github.rosemoe.sora.text.Content.subContentInternal(Content.java:719)
	at io.github.rosemoe.sora.text.Content.subSequence(Content.java:192)
	at io.github.rosemoe.sora.widget.EditorInputConnection.getTextRegionInternal(EditorInputConnection.java:138)
	at io.github.rosemoe.sora.widget.EditorInputConnection.getTextRegion(EditorInputConnection.java:172)
	at io.github.rosemoe.sora.widget.EditorInputConnection.getSelectedText(EditorInputConnection.java:185)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:284)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by MrIkso** [comment]
Use latest build from GitHub Actions

**Comment by itsaky** [comment]
This should be reported to [`sora-editor`](https://github.com/Rosemoe/sora-editor).
