### ISSUE TITLE
A BUG

### ISSUE THREAD

**Issue by bilicainiaohh** [itsaky/AndroidIDE#151]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - Device: [e.g. realme 3 Pro]
 - OS: [e.g. Android 11]
 - AndroidIDE Version [e.g. v1.0.3-alpha]

**Additional context**

AndroidIDE crash report
Manufacturer: HUAWEI
Device: ANA-AN00
App version: 2.0.0-beta (200)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: start 0, end 45, s.length() 44
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
	at java.lang.StringBuilder.append(StringBuilder.java:176)
	at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:47)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:14)
	at io.github.rosemoe.sora.widget.CodeEditor.deleteText(CodeEditor.java:10)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(CodeEditor.java:154)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3099)
	at android.view.View.dispatchKeyEvent(View.java:13633)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:729)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:2001)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4140)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:1)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:2)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:577)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6343)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6211)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5623)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5781)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5631)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5838)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5631)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5604)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8698)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8618)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8571)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5352)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by itsaky** [comment]
Report in [`sora-editor`](https://github.com/Rosemoe/sora-editor).
