### ISSUE TITLE
code view

### ISSUE THREAD

**Issue by mshdabiola** [itsaky/AndroidIDE#155]
AndroidIDE crash report
Manufacturer: INFINIX MOBILITY LIMITED
Device: InfinixX650B
App version: 2.0.0-beta (200)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: start 0, end 19, s.length() 8
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:546)
	at java.lang.StringBuilder.append(StringBuilder.java:176)
	at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:47)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:14)
	at io.github.rosemoe.sora.text.UndoManager$InsertAction.undo(UndoManager.java:1)
	at io.github.rosemoe.sora.widget.CodeEditor.undo(CodeEditor.java:6)
	at com.itsaky.androidide.EditorActivity.onOptionsItemSelected(EditorActivity.java:137)
	at android.app.Activity.onMenuItemSelected(Activity.java:3543)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:1)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:1)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:1)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:8)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:5)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:2)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
	at android.view.View.performClick(View.java:7044)
	at android.view.View.performClickInternal(View.java:7017)
	at android.view.View.access$3200(View.java:784)
	at android.view.View$PerformClick.run(View.java:26596)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6819)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)

**Comment by itsaky** [comment]
This must be reported to [`sora-editor`](https://github.com/Rosemoe/sora-editor).
