### ISSUE TITLE
[BUG] Editor crash while deleting text

### ISSUE THREAD

**Issue by itsvks19** [itsaky/AndroidIDE#161]
AndroidIDE crash report
Manufacturer: samsung
Device: SM-F127G
App version: 2.0.1-beta (201)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'int io.github.rosemoe.sora.text.CharPosition.line' on a null object reference
	at io.github.rosemoe.sora.text.CachedIndexer.afterDelete(CachedIndexer.java:440)
	at io.github.rosemoe.sora.text.Content.dispatchAfterDelete(Content.java:835)
	at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:505)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:407)
	at io.github.rosemoe.sora.widget.CodeEditor.deleteText(CodeEditor.java:1625)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(CodeEditor.java:3417)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3624)
	at android.view.View.dispatchKeyEvent(View.java:15050)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:903)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1947)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4142)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3090)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:758)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7365)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7191)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6206)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by itsaky** [comment]
Please report this to [sora-editor](https://github.com/Rosemoe/sora-editor).
