### ISSUE TITLE
Installation error android ide

### ISSUE THREAD

**Issue by Holak01** [itsaky/AndroidIDE#187]
```
AndroidIDE crash report
Manufacturer: HUAWEI
Device: MRD-LX1
App version: 2.0.1-beta (201)

 Stacktrace: 
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:6)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:14)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:20)
	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:1)
	at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(BottomSheetDialogFragment.java:2)
	at com.itsaky.androidide.fragments.sheets.ProgressSheet.dismiss(ProgressSheet.java:1)
	at com.itsaky.androidide.DownloadActivity$$ExternalSyntheticLambda6.run(R8$$SyntheticClass:12)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

***This is the error I got on installing the plugins***

**Comment by Wendors** [comment]
![Screenshot_2022-05-16-19-35-28-42_9ad8e654efd333b66ab21513aa36e36c.jpg](https://user-images.githubusercontent.com/31355465/168641596-340c7306-9b6b-443d-9842-fcf3e7bf3589.jpg)

**Comment by itsaky** [comment]
The installation process has been changed. This issue should not occur now.
