### ISSUE TITLE
When we search in project then select any result

### ISSUE THREAD

**Issue by ani1nonly** [itsaky/AndroidIDE#195]
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiK20Pro
App version: 2.0.2-beta (202)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=128; index=-1
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:255)
	at io.github.rosemoe.sora.widget.layout.LineBreakLayout.getCharLayoutOffset(LineBreakLayout.java:168)
	at io.github.rosemoe.sora.widget.CursorBlink.run(CursorBlink.java:81)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by itsaky** [comment]
Fixed in 2bc1838f764bbcee383326ab76c82fa3dbf7c441.
