### ISSUE TITLE
Got the following after exiting.

### ISSUE THREAD

**Issue by Trasd** [itsaky/AndroidIDE#199]
```
AndroidIDE crash report
Manufacturer: LENOVO
Device: LenovoTB-J706F
App version: 2.0.2-beta (202)

 Stacktrace: 
java.lang.IllegalStateException: Already closed
	at leakcanary.internal.activity.db.ScopedLeaksDb$DbOpener.checkClosed(ScopedLeaksDb.kt:69)
	at leakcanary.internal.activity.db.ScopedLeaksDb$DbOpener.getWritableDatabase(ScopedLeaksDb.kt:51)
	at leakcanary.internal.activity.db.Db$execute$1.invoke(Db.kt:35)
	at leakcanary.internal.activity.db.Db$execute$1.invoke(Db.kt:9)
	at leakcanary.internal.activity.db.Io$execute$2.invoke(Io.kt:44)
	at leakcanary.internal.activity.db.Io$execute$2.run(Io.kt:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by Trasd** [comment]
No problem.  Thanks.
