### ISSUE TITLE
Creating new kotlin project cases a error. 

### ISSUE THREAD

**Issue by Agono0** [itsaky/AndroidIDE#205]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - Device: [e.g.  Samsung J7 pro]
 - OS: [e.g. Android 9]
 - AndroidIDE Version [e.g. lastest from Action]

**Additional context**

Build is stuck in " Starting build..."
When start new kotlin project...

Error :

```
java.lang.IllegalStateException: Missing header Content-Length in input "{"jsonrpc":"2.0","method":"client/onProgressEvent","params":{"progress":85991593,"total":115847608,"unit":"bytes","displayName":"Download https://services.gradle.org/distributions/gradle-7.4-bin.zip 85991593/115847608 bytes completed","eventTime":1654285819009,"descriptor":{"uri":"https://services.gradle.org/distributions/gradle-7.4-bin.zip","name":"Download https://services.gradle.org/distributions/gradle-7.4-bin.zip","displayName":"Download https://services.gradle.org/distributions/gradle-7.4-bin.zip","gsonType":"com.itsaky.androidide.tooling.events.download.FileDownloadOperationDescriptor"},"gsonType":"com.itsaky.androidide.tooling.events.StatusEvent"}}.Content-Length: 664
StreamMessageProducer     E  
StreamMessageProducer     E  "
StreamMessageProducer     E  	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:85)
StreamMessageProducer     E  	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:120)
StreamMessageProducer     E  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
StreamMessageProducer     E  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
StreamMessageProducer     E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
StreamMessageProducer     E  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
StreamMessageProducer     E  	at java.lang.Thread.run(Thread.java:764)
StreamMessageProducer     E   Missing header Content-Length in input "{"jsonrpc":"2.0","method":"client/onProgressEvent","params":{"progress":87040169,"total":115847608,"unit":"bytes","displayName":"Download https://services.gradle.org/distributions/gradle-7.4-bin.zip 87040169/115847608 bytes completed","eventTime":1654285821080,"descriptor":{"uri":"https://services.gradle.org/distributions/gradle-7.4-bin.zip","name":"Download https://services.gradle.org/distributions/gradle-7.4-bin.zip","displayName":"Download https://services.gradle.org/distributions/gradle-7.4-bin.zip","gsonType":"com.itsaky.androidide.tooling.events.download.FileDownloadOperationDescriptor"},"gsonType":"com.itsaky.androidide.tooling.events.StatusEvent"}}.Content-Length: 664
StreamMessageProducer     E  
```

**Comment by BanDroid** [comment]
Its not related to the kotlin project, i think its your internet connections problem, try to delete cache from androidide app in settings, and try to open this project again with stable and fast internet.

For better result, try to clean and build.

**Comment by Agono0** [comment]
@BanDroid
It's not internet connection problem,  because my internet works fine and when i open old project open successfully, and i declare the same gradle version which i use in every project (7.4)
So i thinks the problem not from me.
I can't clean and rebuild because the build didn't start !!!
The error is getting repeated, that's all about

**Comment by A0ks9** [comment]
> Its not related to the kotlin project, i think its your internet connections problem, try to delete cache from androidide app in settings, and try to open this project again with stable and fast internet.
> 
> For better result, try to clean and build.

dude i have the same error , the error isnt from my internet.
