### ISSUE TITLE
LogSender: IllegalThreadStateException

### ISSUE THREAD

**Issue by itsaky** [itsaky/AndroidIDE#21]
LogSender crashes when it is started with the following stacktrace:
```
Caused by: java.lang.IllegalThreadStateException
11-01  22:16:07.059  10611  10611  E  AndroidRuntime: at java.lang.Thread.start(Thread.java:724)
11-01  22:16:07.059  10611  10611  E  AndroidRuntime: at com.itsaky.androidide.logsender.LogSender.startLogging(LogSender.java:58)
11-01  22:16:07.059  10611  10611  E  AndroidRuntime: at <__package__>.MainActivity.onCreate(MainActivity.kt:39)
```

**Comment by itsaky** [comment]
Has been fixed.
