### ISSUE TITLE
AndroidIDE crash

### ISSUE THREAD

**Issue by matrixcri** [itsaky/AndroidIDE#228]
AndroidIDE crash
```
 Stacktrace: 
java.lang.IllegalStateException: Tooling API server has not been started
	at com.itsaky.androidide.services.GradleBuildService.checkServerStarted(GradleBuildService.java:358)
	at com.itsaky.androidide.services.GradleBuildService.initializeProject(GradleBuildService.java:292)
	at com.itsaky.androidide.EditorActivity.initializeProject(EditorActivity.java:911)
	at com.itsaky.androidide.actions.build.ProjectSyncAction.execAction(ProjectSyncAction.kt:44)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda-1$lambda-0(DefaultActionsRegistry.kt:136)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$x3ssCnNYbdbBmuWXXzMq_mom94U(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda-1(DefaultActionsRegistry.kt:135)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$4QU30ZUG4MYnuZmK2rBaEKzRdQM(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:6)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1219)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3230)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4202)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3944)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:218)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
	at android.view.View.dispatchTouchEvent(View.java:13483)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2767)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2581)
	at android.view.View.dispatchPointerEvent(View.java:13744)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5601)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5401)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4902)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4921)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5061)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4929)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5118)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4902)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4921)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4929)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4902)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7654)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7623)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7584)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7785)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:251)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:180)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by matrixcri** [comment]
And one more gradel file download doesn't work.

**Comment by MrIkso** [comment]
Try use latest build from GitHub actions

**Comment by matrixcri** [comment]
> Try use latest build from GitHub actions

this is the latest version.

**Comment by BanDroid** [comment]
He means latest version from github actions, not latest release.

**Comment by matrixcri** [comment]
> He means latest version from github actions, not latest release.

Yes it is from action not from release.

**Comment by itsaky** [comment]
Is there any specific way to reproduce this? I cannot reproduce the error.

This could probably happen if the JDK is not installed.

**Comment by itsaky** [comment]
Happens when JDK is not installed. Please make sure that the JDK is installed properly then try again. Follow the [instructions](https://github.com/itsaky/androidide-build-tools) properly.
