### ISSUE TITLE
Terminal not opening

### ISSUE THREAD

**Issue by ani1nonly** [itsaky/AndroidIDE#234]
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiK20Pro
App version: 2.1.2-beta (212)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
	at com.itsaky.androidide.views.virtualkeys.SpecialButton.<init>(SpecialButton.java:27)
	at com.itsaky.androidide.views.virtualkeys.SpecialButton.<clinit>(SpecialButton.java:10)
 Caused by: java.lang.ExceptionInInitializerError
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView$1.<init>(VirtualKeysView.java:197)
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView.getDefaultSpecialButtons(VirtualKeysView.java:195)
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView.<init>(VirtualKeysView.java:162)
 Caused by: java.lang.reflect.InvocationTargetException
 Caused by: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
 Caused by: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.itsaky.androidide.databinding.ActivityTerminalBinding.inflate(ActivityTerminalBinding.java:49)
	at com.itsaky.androidide.databinding.ActivityTerminalBinding.inflate(ActivityTerminalBinding.java:43)
	at com.itsaky.androidide.TerminalActivity.bindLayout(TerminalActivity.java:320)
	at com.itsaky.androidide.app.StudioActivity.onCreate(StudioActivity.java:83)
	at com.itsaky.androidide.TerminalActivity.onCreate(TerminalActivity.java:267)
	at android.app.Activity.performCreate(Activity.java:7894)
	at android.app.Activity.performCreate(Activity.java:7881)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.TerminalActivity}: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by MrIkso** [comment]
Its fixed, use latest version from GitHub Actions

**Comment by itsaky** [comment]
@ani1nonly Could you confirm if this is fixed or not?

**Comment by ani1nonly** [comment]
No it is still not opening

**Comment by ani1nonly** [comment]
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiK20Pro
App version: 2.1.2-beta (212)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
	at com.itsaky.androidide.views.virtualkeys.SpecialButton.<init>(SpecialButton.java:27)
	at com.itsaky.androidide.views.virtualkeys.SpecialButton.<clinit>(SpecialButton.java:10)
 Caused by: java.lang.ExceptionInInitializerError
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView$1.<init>(VirtualKeysView.java:197)
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView.getDefaultSpecialButtons(VirtualKeysView.java:195)
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView.<init>(VirtualKeysView.java:162)
 Caused by: java.lang.reflect.InvocationTargetException
 Caused by: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
 Caused by: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.itsaky.androidide.databinding.ActivityTerminalBinding.inflate(ActivityTerminalBinding.java:49)
	at com.itsaky.androidide.databinding.ActivityTerminalBinding.inflate(ActivityTerminalBinding.java:43)
	at com.itsaky.androidide.TerminalActivity.bindLayout(TerminalActivity.java:320)
	at com.itsaky.androidide.app.StudioActivity.onCreate(StudioActivity.java:83)
	at com.itsaky.androidide.TerminalActivity.onCreate(TerminalActivity.java:267)
	at android.app.Activity.performCreate(Activity.java:7894)
	at android.app.Activity.performCreate(Activity.java:7881)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.TerminalActivity}: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by ani1nonly** [comment]
This is from last action build downloaded at 07:10 hours on 28.6.22

**Comment by itsaky** [comment]
Okay. Thanks a lot. I'll look into it.

**Comment by itsaky** [comment]
This is already fixed in the latest commits from main branch.
