### ISSUE TITLE
Tooling API server has not been started

### ISSUE THREAD

**Issue by zaynwinchester** [itsaky/AndroidIDE#251]
```
AndroidIDE crash report
Manufacturer: vivo
Device: V2134
App version: 2.1.2-beta (212)

 Stacktrace: 
java.lang.IllegalStateException: Tooling API server has not been started
	at com.itsaky.androidide.services.GradleBuildService.checkServerStarted(GradleBuildService.java:359)
	at com.itsaky.androidide.services.GradleBuildService.initializeProject(GradleBuildService.java:293)
	at com.itsaky.androidide.EditorActivity.initializeProject(EditorActivity.java:898)
	at com.itsaky.androidide.EditorActivity.lambda$notifySyncNeeded$15$com-itsaky-androidide-EditorActivity(EditorActivity.java:864)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda8.onClick(Unknown Source:2)
	at com.itsaky.androidide.views.MaterialBanner.lambda$show$0$com-itsaky-androidide-views-MaterialBanner(MaterialBanner.java:82)
	at com.itsaky.androidide.views.MaterialBanner$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7512)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3700(View.java:857)
	at android.view.View$PerformClick.run(View.java:29013)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
```

**Comment by itsaky** [comment]
Have you installed JDK and the build tools?

**Comment by itsaky** [comment]
This mostly happens when the JDK is not installed. Please check your installation and try again. You installation instructions are available at [androidide-build-tools](https://github.com/itsaky/androidide-build-tools).

If that's not the case, feel free to reopen this issue.
