### ISSUE TITLE
Unable to open Project

### ISSUE THREAD

**Issue by Petersburg2020** [itsaky/AndroidIDE#255]
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2239
App version: 2.1.1-beta (211)

 Stacktrace: 
com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at com.itsaky.lsp.java.JavaLanguageServer.initialize(JavaLanguageServer.java:139)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1625)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:7980)
	at android.app.Activity.performCreate(Activity.java:7969)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3503)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3532)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3687)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7824)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

**Comment by itsaky** [comment]
Please provide a way to reproduce this issue.

**Comment by Petersburg2020** [comment]
Send it to my mail
