### ISSUE TITLE
Crashes on clicking ok "You need to install jdk, sdk..." at startup

### ISSUE THREAD

**Issue by 54b1d** [itsaky/AndroidIDE#262]
I have external sdcard formatted as internal. Probably it's causing the issue. Moving app into Internal Storage fixes it. Low Priority, but being fixed would help my low internal storage.

App is installed at "/mnt/expand/187b324c-e6c8-4a18-b229-6cbc4449b5ad/app/com.itsaky.androidide-DNzTqT-xpIa3Pl_v-IKJvg==/base.apk".
AppData is at "/mnt/expand/187b324c-e6c8-4a18-b229-6cbc4449b5ad/user/0/com.itsaky.androidide/"

AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi5
App version: 2.1.2-beta (212)

 Stacktrace: 
com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
 Caused by: java.util.concurrent.CompletionException: com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:110)
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by itsaky** [comment]
Sorry. This is not possible. AndroidIDE includes a lot of executable binaries. Those binary files can only be executed in the root directory.
