### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Suryabahadurgauli** [itsaky/AndroidIDE#275]
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: 21061119BI
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:220)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1618)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:8142)
	at android.app.Activity.performCreate(Activity.java:8114)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1308)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3564)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3591)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3763)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2202)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8069)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by itsaky** [comment]
Duplicate of #235.
