### ISSUE TITLE
NullPointerException during search in project.

### ISSUE THREAD

**Issue by AndreyKozhev** [itsaky/AndroidIDE#276]
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2006C3MNG
App version: 2.1.2-beta (212)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.CheckBox.isChecked()' on a null object reference
	at com.itsaky.androidide.EditorActivity.lambda$createFindInProjectDialog$40$com-itsaky-androidide-EditorActivity(EditorActivity.java:1627)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda11.onClick(Unknown Source:6)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```
# Steps to reproduce
Open several files (in my case 2), select the "Search in project" option, enter the text for the search and extension, click "Find".
If the files are not open or only one file is open, the error does not appear.
# Screenshots
![Screenshot](https://user-images.githubusercontent.com/103951737/178227562-24b9cfc3-8ac9-4729-91b5-f9b9e695d5c0.jpg)

![Screenshot](https://user-images.githubusercontent.com/103951737/178247415-dc559891-b711-4ae4-8391-22d05d71f18f.jpg)

Unfortunately, the screenshots are in the Russian locale.

**Comment by AndreyKozhev** [comment]
The problem is that this occurs when the project is initialized.
