### ISSUE TITLE
Error `Tooling API server is already started` when reopening AndroidIDE

### ISSUE THREAD

**Issue by AndreyKozhev** [itsaky/AndroidIDE#318]
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2006C3MNG
App version: 2.1.2-beta (212)

 Stacktrace: 
com.itsaky.androidide.services.ToolingServerAlreadyStartedException: Tooling API server is already started
	at com.itsaky.androidide.services.GradleBuildService.startToolingServer(GradleBuildService.java:394)
	at com.itsaky.androidide.EditorActivity$1.onServiceConnected(EditorActivity.java:190)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1958)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1990)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```
# Steps to reproduce
The same as in #264.

**Comment by itsaky** [comment]
Fixed in #325.
