### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by jundy779** [itsaky/AndroidIDE#324]
![Screenshot_2022-07-20-16-36-12-961_com itsaky androidide](https://user-images.githubusercontent.com/54092710/179950267-30cadfb3-c3d3-400b-afa4-66e27519c2a3.jpg)
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2103K19PG
App version: 2.1.2-beta (212)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index: 6, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(AsyncIncrementalAnalyzeManager.java:442)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:831)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:451)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:145)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3574)
	at android.view.View.draw(View.java:23146)
	at android.view.View.updateDisplayListIfDirty(View.java:21973)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:21913)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4830)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4536)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3629)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2356)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1129)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:840)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1114)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8298)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by MatheusTGamerPro** [comment]
Could you tell me better when and where this error happens?

**Comment by itsaky** [comment]
Write a proper title for issues/PRs. And provide a way to reproduce this bug.
