### ISSUE TITLE
AndroidIDE ERROR

### ISSUE THREAD

**Issue by cumaRull** [itsaky/AndroidIDE#343]
```
AndroidIDE crash report
Manufacturer: realme
Device: RMX3191
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.IllegalStateException: Tooling API server has not been started
	at com.itsaky.androidide.services.GradleBuildService.checkServerStarted(GradleBuildService.java:358)
	at com.itsaky.androidide.services.GradleBuildService.initializeProject(GradleBuildService.java:292)
	at com.itsaky.androidide.EditorActivity.initializeProject(EditorActivity.java:911)
	at com.itsaky.androidide.actions.build.ProjectSyncAction.execAction(ProjectSyncAction.kt:44)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda-1$lambda-0(DefaultActionsRegistry.kt:136)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$x3ssCnNYbdbBmuWXXzMq_mom94U(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda-1(DefaultActionsRegistry.kt:135)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$4QU30ZUG4MYnuZmK2rBaEKzRdQM(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:6)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:352)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1234)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3231)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4265)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3986)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:218)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
	at android.view.View.dispatchTouchEvent(View.java:14668)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2853)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2573)
	at android.view.View.dispatchPointerEvent(View.java:14940)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6992)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6763)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6228)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6290)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6251)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6425)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6259)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6482)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6232)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6290)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6251)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6259)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6232)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9372)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9312)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9258)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9526)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:265)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:179)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
```

**Comment by itsaky** [comment]
Duplicate of #251.
