### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shinian-a** [itsaky/AndroidIDE#390]
### What happened?

collapse

### What's the expected behavior?

..

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: HUAWEI
Device: JEF-AN00
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.IllegalStateException: Tooling API server has not been started
	at com.itsaky.androidide.services.GradleBuildService.checkServerStarted(GradleBuildService.java:358)
	at com.itsaky.androidide.services.GradleBuildService.initializeProject(GradleBuildService.java:292)
	at com.itsaky.androidide.EditorActivity.initializeProject(EditorActivity.java:911)
	at com.itsaky.androidide.actions.build.ProjectSyncAction.execAction(ProjectSyncAction.kt:44)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda-1$lambda-0(DefaultActionsRegistry.kt:136)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$x3ssCnNYbdbBmuWXXzMq_mom94U(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda-1(DefaultActionsRegistry.kt:135)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$4QU30ZUG4MYnuZmK2rBaEKzRdQM(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:6)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1397)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3494)
	at android.widget.AbsListView$5.run(AbsListView.java:4543)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
Please search before creating issues.
This issue is already reported in #251 and also fixed. Wait for the next release.

**Comment by deepkrg17** [comment]
Please search before creating issues.
This issue is already reported in #251.
