### ISSUE TITLE
[Bug]:  Crash to open app

### ISSUE THREAD

**Issue by PixelCodeCu** [itsaky/AndroidIDE#403]
### What happened?

When leaving the app and returning to it, the bug appeared

### What's the expected behavior?

Open the app

### What version of AndroidIDE you're using?

v2.1.1

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G973U1
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'android.widget.HorizontalScrollView com.itsaky.androidide.databinding.LayoutEditorFileTreeBinding.filetreeHorizontalScrollView' on a null object reference
	at com.itsaky.androidide.fragments.FileTreeFragment.getScrollView(FileTreeFragment.java:294)
	at com.itsaky.androidide.fragments.FileTreeFragment.lambda$listProjectFiles$4$com-itsaky-androidide-fragments-FileTreeFragment(FileTreeFragment.java:261)
	at com.itsaky.androidide.fragments.FileTreeFragment$$ExternalSyntheticLambda0.complete(Unknown Source:4)
	at com.itsaky.androidide.tasks.TaskExecutor.lambda$executeAsync$1(TaskExecutor.java:48)
	at com.itsaky.androidide.tasks.TaskExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
Search one time before creating a issue.
This issue is already reported in #260 and also fixed.
