### ISSUE TITLE
Code Editor Crashed

### ISSUE THREAD

**Issue by faultydevil23** [itsaky/AndroidIDE#425]
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2095
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.progressindicator.LinearProgressIndicator com.itsaky.androidide.databinding.ActivityEditorBinding.buildProgressIndicator' on a null object reference
	at com.itsaky.androidide.EditorActivity.lambda$onProjectInitialized$19$com-itsaky-androidide-EditorActivity(EditorActivity.java:934)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda16.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by itsaky** [comment]
This was already reported and fixed. And use the issue templates for new issues.
