### ISSUE TITLE
[BUG] Design View Crash App

### ISSUE THREAD

**Issue by droidalfa** [itsaky/AndroidIDE#45]
___________🅳🅴🆂🅸🅶🅽 🆅🅸🅴🆅 🅱🆄🅶___________
![Screenshot_2022-01-08-12-23-52-892_com itsaky androidide](https://user-images.githubusercontent.com/33790563/148639042-6e0d2676-7df1-48aa-8010-72b386c2cb32.jpg)

I create my android project then open any file res/layout/.xml then when opening design view the app crashes giving the error in the crash report below
////////////////////////////////////////////////////////////////////////////////

AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote6Pro
App version: 2.0-beta (200)

```
 Stacktrace: 
java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY.
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1090)
	at android.view.View.measure(View.java:23196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23196)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1656)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:601)
	at android.view.View.measure(View.java:23196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:99)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2003)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
	at android.view.View.measure(View.java:23196)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:23196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:23196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23196)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:720)
	at android.view.View.measure(View.java:23196)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2798)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1646)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1930)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1534)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7421)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
	at android.view.Choreographer.doFrame(Choreographer.java:819)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by itsaky** [comment]
Does it happen with the APK from the [latest commit](https://github.com/itsaky/AndroidIDE/actions/runs/1670776421)?

**Comment by droidalfa** [comment]
![Screenshot_2022-01-08-12-56-15-075_com itsaky androidide](https://user-images.githubusercontent.com/33790563/148639972-05538aad-7b17-4f84-88d9-fb2c0f01e76b.jpg)

I downloaded the latest version and it didn't give an error in the design view but it gives an error when adding the Button,TextView... widgets

AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote6Pro
App version: 2.0-beta (200)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.itsaky.inflater.impl.UiViewGroup.getChildAt(UiViewGroup.java:107)
	at com.itsaky.androidide.ui.WidgetDragListener.findPlaceHolderIndex(WidgetDragListener.java:127)
	at com.itsaky.androidide.ui.WidgetDragListener.onDrag(WidgetDragListener.java:82)
	at android.view.View.callDragEventHandler(View.java:24277)
	at android.view.ViewRootImpl.setDragFocus(ViewRootImpl.java:6652)
	at android.view.View.dispatchDragEvent(View.java:24266)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1776)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6531)
	at android.view.ViewRootImpl.access$1000(ViewRootImpl.java:139)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4398)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
