### ISSUE TITLE
[BUG] Sysroot directory doesn't exist error in latest alpha

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [itsaky/AndroidIDE#47]
**1st Error in gradle build**
> Cannot create service of type BuildTreeActionExecutor using method LauncherServices$ToolingBuildTreeScopeServices.createActionExecutor() as there is a problem with parameter #1 of type List<BuildActionRunner>.
> Could not create service of type BuildLifecycleAwareVirtualFileSystem using GradleUserHomeServices.createVirtualFileSystem().
> java.io.IOException: java.io.tmpdir is set to a directory that doesn't exist: ROOT/sysroot/tmp

**2nd Terminal bootstrap installation error**
![Screenshot_2022-01-09-22-34-36-758_com itsaky androidide](https://user-images.githubusercontent.com/72644801/148693035-2fe89398-002a-4c34-88b6-7d378042f7e0.jpg)

**Comment by Premjit-Chowdhury** [comment]
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2102J20SI
App version: 2.0-beta (200)

 Stacktrace: 
com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to delete sysroot directory
 Caused by: java.util.concurrent.CompletionException: com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to delete sysroot directory
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:75)
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
