### ISSUE TITLE
AndroidIdE crashed trying to open Terminal

### ISSUE THREAD

**Issue by CodeJoker01** [itsaky/AndroidIDE#59]
```
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A115F
App version: 2.0-beta (200)
OS: Android 11

Stacktrace: 
android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8373)
	at libcore.io.IoBridge.open(IoBridge.java:478)
 Caused by: java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:121)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less: open failed: EACCES (Permission denied)
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:165)
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less: open failed: EACCES (Permission denied)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1666)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by stayaway49** [comment]
@CodeJoker01 @itsaky why is this happening. It always crashes.

**Comment by itsaky** [comment]
This can be fixed by following these steps :
- Set the terminal to use system in preferences (`Preferences -> General -> Use system shell`).
- Open terminal and delete the sysroot directory (`rm -rvf $SYSROOT`)
- Exit terminal
- Disable the switch you enabled in `step 1`
- Restart AndroidIDE
- Open terminal

The bootstrap packages will then be installed.
