### ISSUE TITLE
AndroidIDE's autocompletion is not working

### ISSUE THREAD

**Issue by CodeJoker01** [itsaky/AndroidIDE#68]
```
Manufacturer: samsung 
Device: SM-A115F 
App version: 2.0-beta (200) 
Os: Android 11 

CodeEditor: An error occurred while finding signature help java.lang.RuntimeException: Compiler is still in-use!
    at com.itsaky.lsp.java.compiler.JavaCompilerService.loadCompile(JavaCompilerService.java:97)
    at com.itsaky.lsp.java.compiler.JavaCompilerService.compileBatch(JavaCompilerService.java:135)
    at com.itsaky.lsp.java.compiler.JavaCompilerService.compile(JavaCompilerService.java:354)
    at com.itsaky.lsp.java.compiler.JavaCompilerService.lambda$compile$2$com-itsaky-lsp-java-compiler-JavaCompilerService(JavaCompilerService.java:347)
    at com.itsaky.lsp.java.compiler.JavaCompilerService$$ExternalSyntheticLambda1.apply(Unknown Source:6)
    at com.itsaky.lsp.java.compiler.SynchronizedTask.getWithTask(SynchronizedTask.java:52)
    at com.itsaky.lsp.java.compiler.JavaCompilerService.compile(JavaCompilerService.java:342)
    at com.itsaky.lsp.java.providers.SignatureProvider.signatureHelp(SignatureProvider.java:98)
    at com.itsaky.lsp.java.providers.SignatureProvider.provideSignatures(SignatureProvider.java:86)
    at io.github.rosemoe.editor.widget.CodeEditor.lambda$signatureHelp$9$io-github-rosemoe-editor-widget-CodeEditor(CodeEditor.java:4569)
    at io.github.rosemoe.editor.widget.CodeEditor$$ExternalSyntheticLambda6.get(Unknown Source:2)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1627)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Compiler is still in-use!
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1629)
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1619)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by dhaigit** [comment]
When that happens, just backspace some letters and try again. It should work after after a few retries. If not, just select assembleDebug and wait a moment for it to finish, then start using auto completion.

**Comment by Wendors** [comment]
> When that happens, just backspace some letters and try again. It should work after after a few retries. If not, just select assembleDebug and wait a moment for it to finish, then start using auto completion.

I also do not have autocomplete code even with your instructions

**Comment by itsaky** [comment]
Check out with the [latest commit](https://github.com/itsaky/AndroidIDE/actions/runs/1738581444).

**Comment by itsaky** [comment]
Closing this issue as there was no response from the author.
