### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AntroidDev** [itsaky/AndroidIDE#88]
```
AndroidIDE crash report
Manufacturer: HUAWEI
Device: SNE-LX3
App version: 2.0-beta (200)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at io.github.rosemoe.editor.text.CachedIndexer.afterInsert(CachedIndexer.java:410)
	at io.github.rosemoe.editor.text.Cursor.afterInsert(Cursor.java:519)
	at io.github.rosemoe.editor.text.Content.dispatchAfterInsert(Content.java:783)
	at io.github.rosemoe.editor.text.Content.insert(Content.java:326)
	at io.github.rosemoe.editor.text.Cursor.onCommitText(Cursor.java:313)
	at io.github.rosemoe.editor.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:231)
	at io.github.rosemoe.editor.widget.EditorInputConnection.commitText(EditorInputConnection.java:200)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:339)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by itsaky** [comment]
Try using a newer version. The editor has been updated.
