### ISSUE TITLE
App crashes when switching from default vertical floating text action to horizontal

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#93]
To reproduce:

1. Make sure floating text actions preference is in vertical (default) mode

2. Make a text selection

3. Keep the floating text actions popup on while going to IDE-preferences->Editor and turn on "Horizontal text actions"

4. Tap device's back key twice to return to editor

5. The old floating text actions popup is now stuck on screen

6. Try to make a text selection and the app would crash

[edit with error log]

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4989)
	at android.view.ViewGroup.addView(ViewGroup.java:4820)
	at android.view.ViewGroup.addView(ViewGroup.java:4777)
	at android.widget.PopupWindow.createDecorView(PopupWindow.java:1421)
	at android.widget.PopupWindow.preparePopup(PopupWindow.java:1369)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1215)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1187)
	at io.github.rosemoe.sora.widget.base.EditorPopupWindow.applyWindowAttributes(EditorPopupWindow.java:214)
	at io.github.rosemoe.sora.widget.base.EditorPopupWindow.show(EditorPopupWindow.java:272)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow.show(EditorTextActionWindow.java:161)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow.displayWindow(EditorTextActionWindow.java:252)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

**Comment by itsaky** [comment]
If the app crashes, you're expected to show the stacktrace too.
