### ISSUE TITLE
[BUG] Invalid selection range when selecting diagnostic item or search result item.

### ISSUE THREAD

**Issue by imdadul28** [itsaky/AndroidIDE#99]
AndroidIDE crash report
Manufacturer: realme
Device: RMX2001
App version: 2.0-beta (200)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: Column 142 out of bounds.line: 25 ,column count:139
	at io.github.rosemoe.sora.text.Content.checkLineAndColumn(Content.java:892)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:391)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:384)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharIndex(CachedIndexer.java:342)
	at io.github.rosemoe.sora.text.Content.getCharIndex(Content.java:315)
	at io.github.rosemoe.sora.widget.CodeEditor.setSelectionRegion(CodeEditor.java:4009)
	at io.github.rosemoe.sora.widget.CodeEditor.setSelectionRegion(CodeEditor.java:3981)
	at com.itsaky.androidide.EditorActivity.lambda$openFileAndSelect$10(EditorActivity.java:653)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda25.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by itsaky** [comment]
@imdadul28
It should probably work in the latest commit. I assume this occurs when you click on a diagnostic or search result item from the list. It'll be helpful if you provide a proper way to reproduce the error.

**Comment by itsaky** [comment]
Closing this issue as there was no response from the author.
